### ISSUE TITLE
Token support

### ISSUE THREAD

**Issue by axel3rd** [GroupePSA/sonarqube-cleanup-cli#11]
Currently connection with token throw error:

```
Connecting to        : http://sonarqube.company.com (user: 0420000000000000000000000000000000000042)
Exception in thread "main" java.lang.UnsupportedOperationException: Unsupported status code: 401 Unauthorized
        at org.psa.sonarqube.cleanup.rest.AbstractClient.call(AbstractClient.java:96)
        at org.psa.sonarqube.cleanup.rest.AbstractClient.post(AbstractClient.java:53)
        at org.psa.sonarqube.cleanup.rest.AbstractClient.post(AbstractClient.java:49)
        at org.psa.sonarqube.cleanup.rest.SonarQubeClient.build(SonarQubeClient.java:32)
        at org.psa.sonarqube.cleanup.SonarQubeCleanupCli.main(SonarQubeCleanupCli.java:21)
```

**Comment by axel3rd** [comment]
Root cause: When token is used, `api/authentication/login` usage is useless
